version: "1.0"
mongodb:
  enabled: false
  skip_migration: true
  use_external: true
  connection_string_env: MONGO_URL
services:
  backend:
    build_path: ./backend
    port: 8001
    env_file: ./backend/.env
  frontend:
    build_path: ./frontend
    port: 3000
    env_file: ./frontend/.env
